trigger: 
    branches: 
        include: 
            - develop

pr: none # will disable PR builds 

pool:
  vmImage: ubuntu-latest

variables:
- template: variables.yml
- name: imagetag
  value: default

stages: 
- stage: DeployApi
  jobs:
  - deployment: 
    timeoutInMinutes: 360 
    displayName: Deploy API
    environment: '$(environment).$(namespace)' 
    strategy: 
      runOnce: 
        deploy: 
          steps: 
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'freetrail_sc'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                $imagetag=az acr repository show-tags --name cloudcarbon --repository cloudcarboncalculator/api --top 1 --orderby time_desc --o tsv
                Write-Host "##vso[task.setvariable variable=imagetag;]$imagetag"
          - bash: echo $imagetag
          - task: replacetokens@5
            inputs:
              rootDirectory: '$(System.DefaultWorkingDirectory)/kubernetes'
              targetFiles: 'deployment-api.yml'
              encoding: 'auto'
              tokenPattern: 'default'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false

          - script: cat $(System.DefaultWorkingDirectory)/kubernetes/deployment-api.yml 
            displayName: Print manifest file 
          
          - bash: $imagetag
          - task: KubernetesManifest@0 
            displayName: deploy 
            inputs: 
              namespace: $(namespace)
              manifests: '$(System.DefaultWorkingDirectory)/kubernetes/deployment-api.yml'
              arguments: --env-file=$(System.DefaultWorkingDirectory)/packages/api/.env

- stage: DeployClient
  jobs:
  - deployment: 
    timeoutInMinutes: 360 
    displayName: Deploying Client
    environment: '$(environment).$(namespace)' 
    strategy: 
      runOnce: 
        deploy: 
          steps: 
          - checkout: self
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3 
            displayName: 'Replace tokens in deployment-client.yml' 
            inputs: 
              rootDirectory: "$(System.DefaultWorkingDirectory)/kubernetes" 
              targetFiles: deployment-client.yml 
          - script: cat $(System.DefaultWorkingDirectory)/kubernetes/deployment-client.yml 
            displayName: Print manifest file 
          - task: KubernetesManifest@0 
            displayName: deploy 
            inputs: 
              namespace: $(namespace)
              manifests: '$(System.DefaultWorkingDirectory)/kubernetes/deployment-client.yml'

- stage: Deployingress
  jobs:
  - deployment: 
    timeoutInMinutes: 360 
    displayName: Deploying ingress
    environment: '$(environment).$(namespace)' 
    strategy: 
      runOnce: 
        deploy: 
          steps: 
          - checkout: self
          - script: cat $(System.DefaultWorkingDirectory)/kubernetes/ingress.yml 
            displayName: Print manifest file 
          - task: KubernetesManifest@0 
            displayName: deploy 
            inputs: 
              namespace: $(namespace)
              manifests: '$(System.DefaultWorkingDirectory)/kubernetes/ingress.yml'
