trigger: 
    branches: 
        include: 
            - develop

pr: none # will disable PR builds 

pool: 
  name: "Azure Pipelines"

variables:
- template: variables.yml

stages: 
- stage: DeployApi
  jobs:
  - deployment: 
    timeoutInMinutes: 360 
    displayName: Deploy to $(environment)
    environment: '$(environment).$(namespace)' 
    strategy: 
      runOnce: 
        deploy: 
          steps: 
          - checkout: self
          # - task: AzureCLI@2
          #   inputs:
          #     azureSubscription: 'freetrail_sc'
          #     scriptType: 'core'
          #     scriptLocation: 'inlineScript'
          #     inlineScript: |
          #       $imagetag=az acr repository show-tags --name cloudcarbon --repository cloudcarboncalculator/api --top 1 --orderby time_desc
          #       Write-Host "##vso[task.setvariable variable=imagetag;]$imagetag"
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'freetrail_sc'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                export IMAGE_TAG=$(az acr repository show-tags --name cloudcarbon --repository cloudcarboncalculator/api --top 1 --orderby time_desc)
                echo "##vso[task.setvariable variable=IMAGE_TAG]$IMAGE_TAG"
                echo "IMAGE_TAG: $IMAGE_TAG" >> variables.yml
          # - task: qetza.replacetokens.replacetokens-task.replacetokens@3 
          #   displayName: 'Replace tokens in deployment-api.yml' 
          #   inputs: 
          #     rootDirectory: "$(System.DefaultWorkingDirectory)/kubernetes" 
          #     targetFiles: deployment-api.yml
          
          - task: replacetokens@5
            inputs:
              rootDirectory: '$(System.DefaultWorkingDirectory)/kubernetes'
              targetFiles: 'deployment-api.yml'
              encoding: 'auto'
              tokenPattern: 'default'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              # inlineVariables: |
              #   IMAGE_TAG: "$(IMAGE_TAG)"
          # - task: replacetokens@3
          #   inputs:
          #     targetFiles: '$(System.DefaultWorkingDirectory)/kubernetes'
          #     encoding: 'auto'
          #     writeBOM: true
          #     actionOnMissing: 'warn'
          #     keepToken: false
          #     tokenPrefix: '#{'
          #     tokenSuffix: '}#'


          - script: cat $(System.DefaultWorkingDirectory)/kubernetes/deployment-api.yml 
            displayName: Print manifest file 
          
          - bash: $imagetag
          - task: KubernetesManifest@0 
            displayName: deploy 
            inputs: 
              namespace: $(namespace)
              manifests: '$(System.DefaultWorkingDirectory)/kubernetes/deployment-api.yml'

- stage: DeployClient
  jobs:
  - deployment: 
    timeoutInMinutes: 360 
    displayName: Deploy to $(environment)
    environment: '$(environment).$(namespace)' 
    strategy: 
      runOnce: 
        deploy: 
          steps: 
          - checkout: self
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3 
            displayName: 'Replace tokens in deployment-client.yml' 
            inputs: 
              rootDirectory: "$(System.DefaultWorkingDirectory)/kubernetes" 
              targetFiles: deployment-client.yml 
          - script: cat $(System.DefaultWorkingDirectory)/kubernetes/deployment-client.yml 
            displayName: Print manifest file 
          - task: KubernetesManifest@0 
            displayName: deploy 
            inputs: 
              namespace: $(namespace)
              manifests: '$(System.DefaultWorkingDirectory)/kubernetes/deployment-client.yml'