apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: api
spec: 
  replicas: #{NUM_POD_REPLICAS}# 
  selector: 
    matchLabels: 
      app: api
  template: 
    metadata: 
      labels: 
        app: api
    spec:
      containers: 
      - name: api
        image: #{AZURE_ACR_NAME}#.azurecr.io/cloudcarboncalculator/api:cca030b2d3d45f9e082889700f1590de21ab9260
        ports: 
        - containerPort: 4000
        env:
        - name: AZURE_USE_BILLING_DATA
          value: $AZURE_USE_BILLING_DATA
        - name: AZURE_CLIENT_ID
          value: $AZURE_CLIENT_ID
        - name: AZURE_CLIENT_SECRET
          value: $AZURE_CLIENT_SECRET
        - name: AZURE_TENANT_ID
          value: $AZURE_TENANT_ID
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: api
spec: 
  type: ClusterIP 
  ports: 
  - protocol: TCP 
    port: 4000
    targetPort: 4000
  selector: 
    app: api