apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: client
spec: 
  replicas: #{NUM_POD_REPLICAS}# 
  selector: 
    matchLabels: 
      app: client
  template: 
    metadata: 
      labels: 
        app: client
    spec:
      containers: 
      - name: client
        image: #{AZURE_ACR_NAME}#.azurecr.io/cloudcarboncalculator/client:8327ff7ea05241d79a357388f5c339808bc3fed8
        ports: 
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80