apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: client
spec: 
  replicas: #{NUM_POD_REPLICAS}# 
  selector: 
    matchLabels: 
      app: client
  template: 
    metadata: 
      labels: 
        app: client
    spec:
      containers: 
      - name: client
        image: #{AZURE_ACR_NAME}#.azurecr.io/cloudcarboncalculator/client:b2a1d9c879c50f2e4f1a4364103929ecdde61277
        - containerPort: 80
         volumeMounts:
        - name: nginx-config
          mountPath: /docker/nginx.conf
          subPath: nginx.conf
        - name: other.conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
--- 
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80