apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: client
spec: 
  replicas: #{NUM_POD_REPLICAS}# 
  selector: 
    matchLabels: 
      app: client
  template: 
    metadata: 
      labels: 
        app: client
    spec:
      containers: 
      - name: client
        image: #{AZURE_ACR_NAME}#.azurecr.io/cloudcarboncalculator/client:f497d14223dd9682f3d041b1263e8f5a4af22ef4
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: confnginx
--- 
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80